package com.silvaniastudios.core;

public class CoreUtils {
	
	public static int biomeNameToID(String name) {
		if (name.equalsIgnoreCase("ocean")) { return 0; }
		if (name.equalsIgnoreCase("plains")) { return 1; }
		if (name.equalsIgnoreCase("desert")) { return 2; }
		if (name.equalsIgnoreCase("extreme_hills")) { return 3; }
		if (name.equalsIgnoreCase("forest")) { return 4; }
		if (name.equalsIgnoreCase("taiga")) { return 5; }
		if (name.equalsIgnoreCase("swampland")) { return 6; }
		if (name.equalsIgnoreCase("river")) { return 7; }
		if (name.equalsIgnoreCase("hell")) { return 8; }
		if (name.equalsIgnoreCase("sky")) { return 9; }
		if (name.equalsIgnoreCase("frozen_ocean")) { return 10; }
		if (name.equalsIgnoreCase("frozen_river")) { return 11; }
		if (name.equalsIgnoreCase("ice_flats")) { return 12; }
		if (name.equalsIgnoreCase("ice_mountains")) { return 13; }
		if (name.equalsIgnoreCase("mushroom_island")) { return 14; }
		if (name.equalsIgnoreCase("mushroom_island_shore")) { return 15; }
		if (name.equalsIgnoreCase("beaches")) { return 16; }
		if (name.equalsIgnoreCase("desert_hills")) { return 17; }
		if (name.equalsIgnoreCase("forest_hills")) { return 18; }
		if (name.equalsIgnoreCase("taiga_hills")) { return 19; }
		if (name.equalsIgnoreCase("smaller_extreme_hills")) { return 20; }
		if (name.equalsIgnoreCase("jungle")) { return 21; }
		if (name.equalsIgnoreCase("jungle_hills")) { return 22; }
		if (name.equalsIgnoreCase("jungle_edge")) { return 23; }
		if (name.equalsIgnoreCase("deep_ocean")) { return 24; }
		if (name.equalsIgnoreCase("stone_beach")) { return 25; }
		if (name.equalsIgnoreCase("cold_beach")) { return 26; }
		if (name.equalsIgnoreCase("birch_forest")) { return 27; }
		if (name.equalsIgnoreCase("birch_forest_hills")) { return 28; }
		if (name.equalsIgnoreCase("roofed_forest")) { return 29; }
		if (name.equalsIgnoreCase("taiga_cold")) { return 30; }
		if (name.equalsIgnoreCase("taiga_cold_hills")) { return 31; }
		if (name.equalsIgnoreCase("redwood_taiga")) { return 32; }
		if (name.equalsIgnoreCase("redwood_taiga_hills")) { return 33; }
		if (name.equalsIgnoreCase("extreme_hills_with_trees")) { return 34; }
		if (name.equalsIgnoreCase("savanna")) { return 35; }
		if (name.equalsIgnoreCase("savanna_rock")) { return 36; }
		if (name.equalsIgnoreCase("mesa")) { return 37; }
		if (name.equalsIgnoreCase("mesa_rock")) { return 38; }
		if (name.equalsIgnoreCase("mesa_clear_rock")) { return 39; }
		if (name.equalsIgnoreCase("void")) { return 127; }
		if (name.equalsIgnoreCase("mutated_plains")) { return 129; }
		if (name.equalsIgnoreCase("mutated_desert")) { return 130; }
		if (name.equalsIgnoreCase("mutated_extreme_hills")) { return 131; }
		if (name.equalsIgnoreCase("mutated_forest")) { return 132; }
		if (name.equalsIgnoreCase("mutated_taiga")) { return 133; }
		if (name.equalsIgnoreCase("mutated_swampland")) { return 134; }
		if (name.equalsIgnoreCase("mutated_ice_flats")) { return 140; }
		if (name.equalsIgnoreCase("mutated_jungle")) { return 149; }
		if (name.equalsIgnoreCase("mutated_jungle_edge")) { return 151; }
		if (name.equalsIgnoreCase("mutated_birch_forest")) { return 155; }
		if (name.equalsIgnoreCase("mutated_birch_forest_hills")) { return 156; }
		if (name.equalsIgnoreCase("mutated_roofed_forest")) { return 157; }
		if (name.equalsIgnoreCase("mutated_taiga_cold")) { return 158; }
		if (name.equalsIgnoreCase("mutated_redwood_taiga")) { return 160; }
		if (name.equalsIgnoreCase("mutated_redwood_taiga_hills")) { return 161; }
		if (name.equalsIgnoreCase("mutated_extreme_hills_with_trees")) { return 162; }
		if (name.equalsIgnoreCase("mutated_savanna")) { return 163; }
		if (name.equalsIgnoreCase("mutated_savanna_rock")) { return 164; }
		if (name.equalsIgnoreCase("mutated_mesa")) { return 165; }
		if (name.equalsIgnoreCase("mutated_mesa_rock")) { return 166; }
		if (name.equalsIgnoreCase("mutated_mesa_clear_rock")) { return 167; }
				
		//Biomes o' plenty
		if (name.equalsIgnoreCase("oasis")) { return 97; }
		if (name.equalsIgnoreCase("woodland")) { return 92; }
		if (name.equalsIgnoreCase("white_beach")) { return 41; }
		if (name.equalsIgnoreCase("shrubland")) { return 83; }
		if (name.equalsIgnoreCase("xeric_shrubland")) { return 93; }
		if (name.equalsIgnoreCase("tropical_rainforest")) { return 88; }
		if (name.equalsIgnoreCase("fen")) { return 56; }
		if (name.equalsIgnoreCase("steppe")) { return 86; }
		if (name.equalsIgnoreCase("alps_foothills")) { return 94; }
		if (name.equalsIgnoreCase("bayou")) { return 44; }
		if (name.equalsIgnoreCase("mountain")) { return 70; }
		if (name.equalsIgnoreCase("phantasmagoric_inferno")) { return 106; }
		if (name.equalsIgnoreCase("overgrown_cliffs")) { return 75; }
		if (name.equalsIgnoreCase("highland")) { return 60; }
		if (name.equalsIgnoreCase("volcanic_island")) { return 102; }
		if (name.equalsIgnoreCase("quagmire")) { return 77; }
		if (name.equalsIgnoreCase("marsh")) { return 67; }
		if (name.equalsIgnoreCase("chaparral")) { return 48; }
		if (name.equalsIgnoreCase("flower_island")) { return 103; }
		if (name.equalsIgnoreCase("flower_field")) { return 57; }
		if (name.equalsIgnoreCase("wetland")) { return 91; }
		if (name.equalsIgnoreCase("mystic_grove")) { return 71; }
		if (name.equalsIgnoreCase("cold_desert")) { return 50; }
		if (name.equalsIgnoreCase("mountain_foothills")) { return 95; }
		if (name.equalsIgnoreCase("maple_woods")) { return 66; }
		if (name.equalsIgnoreCase("coral_reef")) { return 98; }
		if (name.equalsIgnoreCase("orchard")) { return 73; }
		if (name.equalsIgnoreCase("moor")) { return 69; }
		if (name.equalsIgnoreCase("land_of_lakes")) { return 61; }
		if (name.equalsIgnoreCase("bog")) { return 45; }
		if (name.equalsIgnoreCase("coniferous_forest")) { return 51; }
		if (name.equalsIgnoreCase("eucalyptus_forest")) { return 55; }
		if (name.equalsIgnoreCase("outback")) { return 74; }
		if (name.equalsIgnoreCase("shield")) { return 82; }
		if (name.equalsIgnoreCase("alps")) { return 42; }
		if (name.equalsIgnoreCase("wasteland")) { return 90; }
		if (name.equalsIgnoreCase("lush_desert")) { return 63; }
		if (name.equalsIgnoreCase("mangrove")) { return 65; }
		if (name.equalsIgnoreCase("boreal_forest")) { return 46; }
		if (name.equalsIgnoreCase("redwood_forest")) { return 79; }
		if (name.equalsIgnoreCase("cherry_blossom_grove")) { return 49; }
		if (name.equalsIgnoreCase("visceral_heap")) { return 109; }
		if (name.equalsIgnoreCase("snowy_forest")) { return 85; }
		if (name.equalsIgnoreCase("seasonal_forest")) { return 81; }
		if (name.equalsIgnoreCase("temperate_rainforest")) { return 87; }
		if (name.equalsIgnoreCase("dead_forest")) { return 53; }
		if (name.equalsIgnoreCase("bamboo_forest")) { return 43; }
		if (name.equalsIgnoreCase("corrupted_sands")) { return 104; }
		if (name.equalsIgnoreCase("dead_swamp")) { return 54; }
		if (name.equalsIgnoreCase("kelp_forest")) { return 99; }
		if (name.equalsIgnoreCase("glacier")) { return 96; }
		if (name.equalsIgnoreCase("meadow")) { return 68; }
		if (name.equalsIgnoreCase("lush_swamp")) { return 64; }
		if (name.equalsIgnoreCase("polar_chasm")) { return 107; }
		if (name.equalsIgnoreCase("fungi_forest")) { return 105; }
		if (name.equalsIgnoreCase("tropical_island")) { return 101; }
		if (name.equalsIgnoreCase("grassland")) { return 58; }
		if (name.equalsIgnoreCase("prairie")) { return 76; }
		if (name.equalsIgnoreCase("snowy_coniferous_forest")) { return 84; }
		if (name.equalsIgnoreCase("tundra")) { return 89; }
		if (name.equalsIgnoreCase("undergarden")) { return 108; }
		if (name.equalsIgnoreCase("origin_island")) { return 100; }
		if (name.equalsIgnoreCase("gravel_beach")) { return 40; }
		if (name.equalsIgnoreCase("grove")) { return 59; }
		if (name.equalsIgnoreCase("lavender_fields")) { return 62; }
		if (name.equalsIgnoreCase("rainforest")) { return 78; }
		if (name.equalsIgnoreCase("sacred_springs")) { return 80; }
		if (name.equalsIgnoreCase("crag")) { return 52; }
		if (name.equalsIgnoreCase("brushland")) { return 47; }
		if (name.equalsIgnoreCase("ominous_woods")) { return 72; }
		
		return Integer.parseInt(name);
	}

}
