package com.silvaniastudios.core;

import com.silvaniastudios.core.config.AlloyBrassConfig;
import com.silvaniastudios.core.config.AlloyBronzeConfig;
import com.silvaniastudios.core.config.AlloyCupronickelConfig;
import com.silvaniastudios.core.config.AlloyElectrumConfig;
import com.silvaniastudios.core.config.AlloyFenikisiteConfig;
import com.silvaniastudios.core.config.AlloyLegeniteConfig;
import com.silvaniastudios.core.config.AlloyNichromeConfig;
import com.silvaniastudios.core.config.AlloyRoseGoldConfig;
import com.silvaniastudios.core.config.AlloySilvamerConfig;
import com.silvaniastudios.core.config.AlloySpeedoiConfig;
import com.silvaniastudios.core.config.AlloyStainlessSteelConfig;
import com.silvaniastudios.core.config.AlloySteelConfig;
import com.silvaniastudios.core.config.AlloyStelliteConfig;
import com.silvaniastudios.core.config.AlloyStrootiteConfig;
import com.silvaniastudios.core.config.AlloyUltimiteConfig;
import com.silvaniastudios.core.config.AlloyUniumConfig;
import com.silvaniastudios.core.config.AluminiumConfig;
import com.silvaniastudios.core.config.AmethystConfig;
import com.silvaniastudios.core.config.BlackstoneConfig;
import com.silvaniastudios.core.config.BluestoneConfig;
import com.silvaniastudios.core.config.ChromiumConfig;
import com.silvaniastudios.core.config.CobaltConfig;
import com.silvaniastudios.core.config.CopperConfig;
import com.silvaniastudios.core.config.CrystalConfig;
import com.silvaniastudios.core.config.DragiteConfig;
import com.silvaniastudios.core.config.FlariteConfig;
import com.silvaniastudios.core.config.FureniumConfig;
import com.silvaniastudios.core.config.LeadConfig;
import com.silvaniastudios.core.config.LithiumConfig;
import com.silvaniastudios.core.config.MagnesiumConfig;
import com.silvaniastudios.core.config.MerciliteConfig;
import com.silvaniastudios.core.config.MythianConfig;
import com.silvaniastudios.core.config.NickelConfig;
import com.silvaniastudios.core.config.PhosphorusConfig;
import com.silvaniastudios.core.config.PlatinumConfig;
import com.silvaniastudios.core.config.PlutoniumConfig;
import com.silvaniastudios.core.config.PurplestoneConfig;
import com.silvaniastudios.core.config.RubyConfig;
import com.silvaniastudios.core.config.SapphireConfig;
import com.silvaniastudios.core.config.SiliconConfig;
import com.silvaniastudios.core.config.SilvaniteConfig;
import com.silvaniastudios.core.config.SilverConfig;
import com.silvaniastudios.core.config.SulfurConfig;
import com.silvaniastudios.core.config.TinConfig;
import com.silvaniastudios.core.config.TitaniumConfig;
import com.silvaniastudios.core.config.TungstenConfig;
import com.silvaniastudios.core.config.UraniumConfig;
import com.silvaniastudios.core.config.VanillaRedstoneConfig;
import com.silvaniastudios.core.config.ZincConfig;

import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;

public class OreDictRegistry {
	
	public static void oreDict() {
		//Block ores
		OreDictionary.registerOre(CopperConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 0));
		OreDictionary.registerOre(TinConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 1));
		OreDictionary.registerOre(ZincConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 2));
		OreDictionary.registerOre(NickelConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 3));
		OreDictionary.registerOre(SilverConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 4));
		OreDictionary.registerOre(AluminiumConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 5));
		OreDictionary.registerOre(TitaniumConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 6));
		OreDictionary.registerOre(ChromiumConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 7));
		OreDictionary.registerOre(SiliconConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 8));
		OreDictionary.registerOre(CobaltConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 9));
		OreDictionary.registerOre(TungstenConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 10));
		OreDictionary.registerOre(LeadConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 11));
		OreDictionary.registerOre(PlatinumConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 12));
		OreDictionary.registerOre(LithiumConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 13));
		OreDictionary.registerOre(UraniumConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 14));
		OreDictionary.registerOre(PlutoniumConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre1, 1, 15));
		OreDictionary.registerOre(RubyConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 0));
		OreDictionary.registerOre(SapphireConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 1));
		OreDictionary.registerOre(AmethystConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 2));
		OreDictionary.registerOre(CrystalConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 3));
		OreDictionary.registerOre(MagnesiumConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 4));
		OreDictionary.registerOre(PhosphorusConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 5));
		OreDictionary.registerOre(SulfurConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 6));
		OreDictionary.registerOre(SilvaniteConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 7));
		OreDictionary.registerOre(MerciliteConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 8));
		OreDictionary.registerOre(MythianConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 9));
		OreDictionary.registerOre(DragiteConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 10));
		OreDictionary.registerOre(FlariteConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 11));
		OreDictionary.registerOre(FureniumConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 12));
		OreDictionary.registerOre(BlackstoneConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 13));
		OreDictionary.registerOre(BluestoneConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 14));
		OreDictionary.registerOre(PurplestoneConfig.oredict.oreOreDict, new ItemStack(ModBlocks.blockOre2, 1, 15));
		
		OreDictionary.registerOre("graphite", new ItemStack(ModBlocks.blockGraphite, 1, 1));
		OreDictionary.registerOre("calcile", new ItemStack(ModBlocks.blockCalcite, 1, 1));
		OreDictionary.registerOre("limestone", new ItemStack(ModBlocks.blockLimestone, 1, 1));
		
		//Item ores
		OreDictionary.registerOre("oreIron", ModItems.oreIron);
		OreDictionary.registerOre("oreGold", ModItems.oreGold);
		OreDictionary.registerOre("dustIron", ModItems.dustIron);
		OreDictionary.registerOre("dustGold", ModItems.dustGold);
		OreDictionary.registerOre("nuggetIron", ModItems.nuggetIron);
		OreDictionary.registerOre("nuggetDiamond", ModItems.nuggetDiamond);
		
		OreDictionary.registerOre(CopperConfig.oredict.oreOreDict, ModItems.oreCopper);
		OreDictionary.registerOre(TinConfig.oredict.oreOreDict, ModItems.oreTin);
		OreDictionary.registerOre(ZincConfig.oredict.oreOreDict, ModItems.oreZinc);
		OreDictionary.registerOre(NickelConfig.oredict.oreOreDict, ModItems.oreNickel);
		OreDictionary.registerOre(SilverConfig.oredict.oreOreDict, ModItems.oreSilver);
		OreDictionary.registerOre(AluminiumConfig.oredict.oreOreDict, ModItems.oreAluminium);
		OreDictionary.registerOre(TitaniumConfig.oredict.oreOreDict, ModItems.oreTitanium);
		OreDictionary.registerOre(ChromiumConfig.oredict.oreOreDict, ModItems.oreChromium);
		OreDictionary.registerOre(SiliconConfig.oredict.oreOreDict, ModItems.oreSilicon);
		OreDictionary.registerOre(CobaltConfig.oredict.oreOreDict, ModItems.oreCobalt);
		OreDictionary.registerOre(TungstenConfig.oredict.oreOreDict, ModItems.oreTungsten);
		OreDictionary.registerOre(LeadConfig.oredict.oreOreDict, ModItems.oreLead);
		OreDictionary.registerOre(PlatinumConfig.oredict.oreOreDict, ModItems.orePlatinum);
		OreDictionary.registerOre(LithiumConfig.oredict.oreOreDict, ModItems.oreLithium);
		OreDictionary.registerOre(UraniumConfig.oredict.oreOreDict, ModItems.oreUranium);
		OreDictionary.registerOre(PlutoniumConfig.oredict.oreOreDict, ModItems.orePlutonium);
		OreDictionary.registerOre(RubyConfig.oredict.oreOreDict, ModItems.oreRuby);
		OreDictionary.registerOre(SapphireConfig.oredict.oreOreDict, ModItems.oreSapphire);
		OreDictionary.registerOre(AmethystConfig.oredict.oreOreDict, ModItems.oreAmethyst);
		OreDictionary.registerOre(CrystalConfig.oredict.oreOreDict, ModItems.oreCrystal);
		OreDictionary.registerOre(MagnesiumConfig.oredict.oreOreDict, ModItems.oreMagnesium);
		OreDictionary.registerOre(PhosphorusConfig.oredict.oreOreDict, ModItems.orePhosphorus);
		OreDictionary.registerOre(SulfurConfig.oredict.oreOreDict, ModItems.oreSulfur);
		OreDictionary.registerOre(SilvaniteConfig.oredict.oreOreDict, ModItems.oreSilvanite);
		OreDictionary.registerOre(MerciliteConfig.oredict.oreOreDict, ModItems.oreMercilite);
		OreDictionary.registerOre(MythianConfig.oredict.oreOreDict, ModItems.oreMythian);
		OreDictionary.registerOre(DragiteConfig.oredict.oreOreDict, ModItems.oreDragite);
		OreDictionary.registerOre(FlariteConfig.oredict.oreOreDict, ModItems.oreFlarite);
		OreDictionary.registerOre(FureniumConfig.oredict.oreOreDict, ModItems.oreFurenium);
		OreDictionary.registerOre(BlackstoneConfig.oredict.oreOreDict, ModItems.oreBlackstone);
		OreDictionary.registerOre(BluestoneConfig.oredict.oreOreDict, ModItems.oreBluestone);
		OreDictionary.registerOre(PurplestoneConfig.oredict.oreOreDict, ModItems.orePurplestone);
		
		//Ingots
		OreDictionary.registerOre(CopperConfig.oredict.ingotOreDict, ModItems.ingotCopper);
		OreDictionary.registerOre(TinConfig.oredict.ingotOreDict, ModItems.ingotTin);
		OreDictionary.registerOre(ZincConfig.oredict.ingotOreDict, ModItems.ingotZinc);
		OreDictionary.registerOre(NickelConfig.oredict.ingotOreDict, ModItems.ingotNickel);
		OreDictionary.registerOre(SilverConfig.oredict.ingotOreDict, ModItems.ingotSilver);
		OreDictionary.registerOre(AluminiumConfig.oredict.ingotOreDict, ModItems.ingotAluminium);
		OreDictionary.registerOre(TitaniumConfig.oredict.ingotOreDict, ModItems.ingotTitanium);
		OreDictionary.registerOre(ChromiumConfig.oredict.ingotOreDict, ModItems.ingotChromium);
		OreDictionary.registerOre(SiliconConfig.oredict.ingotOreDict, ModItems.ingotSilicon);
		OreDictionary.registerOre(CobaltConfig.oredict.ingotOreDict, ModItems.ingotCobalt);
		OreDictionary.registerOre(TungstenConfig.oredict.ingotOreDict, ModItems.ingotTungsten);
		OreDictionary.registerOre(LeadConfig.oredict.ingotOreDict, ModItems.ingotLead);
		OreDictionary.registerOre(PlatinumConfig.oredict.ingotOreDict, ModItems.ingotPlatinum);
		OreDictionary.registerOre(LithiumConfig.oredict.ingotOreDict, ModItems.ingotLithium);
		OreDictionary.registerOre(UraniumConfig.oredict.ingotOreDict, ModItems.ingotUranium);
		OreDictionary.registerOre(PlutoniumConfig.oredict.ingotOreDict, ModItems.ingotPlutonium);
		OreDictionary.registerOre(RubyConfig.oredict.gemOreDict, ModItems.gemRuby);
		OreDictionary.registerOre(SapphireConfig.oredict.gemOreDict, ModItems.gemSapphire);
		OreDictionary.registerOre(AmethystConfig.oredict.gemOreDict, ModItems.gemAmethyst);
		OreDictionary.registerOre(CrystalConfig.oredict.gemOreDict, ModItems.gemCrystal);
		OreDictionary.registerOre(MagnesiumConfig.oredict.ingotOreDict, ModItems.ingotMagnesium);
		OreDictionary.registerOre(SulfurConfig.oredict.ingotOreDict, ModItems.ingotSulfur);
		OreDictionary.registerOre(SilvaniteConfig.oredict.ingotOreDict, ModItems.ingotSilvanite);
		OreDictionary.registerOre(MerciliteConfig.oredict.ingotOreDict, ModItems.ingotMercilite);
		OreDictionary.registerOre(MythianConfig.oredict.ingotOreDict, ModItems.ingotMythian);
		OreDictionary.registerOre(DragiteConfig.oredict.ingotOreDict, ModItems.ingotDragite);
		OreDictionary.registerOre(FlariteConfig.oredict.ingotOreDict, ModItems.ingotFlarite);
		OreDictionary.registerOre(FureniumConfig.oredict.ingotOreDict, ModItems.ingotFurenium);
		OreDictionary.registerOre(BlackstoneConfig.oredict.ingotOreDict, ModItems.ingotBlackstone);
		OreDictionary.registerOre(BluestoneConfig.oredict.ingotOreDict, ModItems.ingotBluestone);
		OreDictionary.registerOre(PurplestoneConfig.oredict.ingotOreDict, ModItems.ingotPurplestone);
		OreDictionary.registerOre(AlloyBronzeConfig.oredict.ingotOreDict, ModItems.ingotBronze);
		OreDictionary.registerOre(AlloyCupronickelConfig.oredict.ingotOreDict, ModItems.ingotCupronickel);
		OreDictionary.registerOre(AlloyBrassConfig.oredict.ingotOreDict, ModItems.ingotBrass);
		OreDictionary.registerOre(AlloyRoseGoldConfig.oredict.ingotOreDict, ModItems.ingotRosegold);
		OreDictionary.registerOre(AlloySteelConfig.oredict.ingotOreDict, ModItems.ingotSteel);
		OreDictionary.registerOre(AlloyStainlessSteelConfig.oredict.ingotOreDict, ModItems.ingotStainlesssteel);
		OreDictionary.registerOre(AlloyNichromeConfig.oredict.ingotOreDict, ModItems.ingotNichrome);
		OreDictionary.registerOre(AlloyElectrumConfig.oredict.ingotOreDict, ModItems.ingotElectrum);
		OreDictionary.registerOre(AlloyStelliteConfig.oredict.ingotOreDict, ModItems.ingotStellite);
		OreDictionary.registerOre(AlloySilvamerConfig.oredict.ingotOreDict, ModItems.ingotSilvamer);
		OreDictionary.registerOre(AlloyUniumConfig.oredict.ingotOreDict, ModItems.ingotUnium);
		OreDictionary.registerOre(AlloyFenikisiteConfig.oredict.ingotOreDict, ModItems.ingotFenikisite);
		OreDictionary.registerOre(AlloyUltimiteConfig.oredict.ingotOreDict, ModItems.ingotUltimite);
		OreDictionary.registerOre(AlloyStrootiteConfig.oredict.ingotOreDict, ModItems.ingotStrootite);
		OreDictionary.registerOre(AlloySpeedoiConfig.oredict.ingotOreDict, ModItems.ingotSpeedoi);
		OreDictionary.registerOre(AlloyLegeniteConfig.oredict.ingotOreDict, ModItems.ingotLegenite);
		OreDictionary.registerOre(VanillaRedstoneConfig.oredict.ingotOreDict, ModItems.ingotRedstone);
		
		//Dusts
		OreDictionary.registerOre(CopperConfig.oredict.dustOreDict, ModItems.dustCopper);
		OreDictionary.registerOre(TinConfig.oredict.dustOreDict, ModItems.dustTin);
		OreDictionary.registerOre(ZincConfig.oredict.dustOreDict, ModItems.dustZinc);
		OreDictionary.registerOre(NickelConfig.oredict.dustOreDict, ModItems.dustNickel);
		OreDictionary.registerOre(SilverConfig.oredict.dustOreDict, ModItems.dustSilver);
		OreDictionary.registerOre(AluminiumConfig.oredict.dustOreDict, ModItems.dustAluminium);
		OreDictionary.registerOre(TitaniumConfig.oredict.dustOreDict, ModItems.dustTitanium);
		OreDictionary.registerOre(ChromiumConfig.oredict.dustOreDict, ModItems.dustChromium);
		OreDictionary.registerOre(SiliconConfig.oredict.dustOreDict, ModItems.dustSilicon);
		OreDictionary.registerOre(CobaltConfig.oredict.dustOreDict, ModItems.dustCobalt);
		OreDictionary.registerOre(TungstenConfig.oredict.dustOreDict, ModItems.dustTungsten);
		OreDictionary.registerOre(LeadConfig.oredict.dustOreDict, ModItems.dustLead);
		OreDictionary.registerOre(PlatinumConfig.oredict.dustOreDict, ModItems.dustPlatinum);
		OreDictionary.registerOre(LithiumConfig.oredict.dustOreDict, ModItems.dustLithium);
		OreDictionary.registerOre(UraniumConfig.oredict.dustOreDict, ModItems.dustUranium);
		OreDictionary.registerOre(PlutoniumConfig.oredict.dustOreDict, ModItems.dustPlutonium);
		OreDictionary.registerOre(RubyConfig.oredict.oreOreDict, ModItems.dustRuby);
		OreDictionary.registerOre(SapphireConfig.oredict.oreOreDict, ModItems.dustSapphire);
		OreDictionary.registerOre(AmethystConfig.oredict.oreOreDict, ModItems.dustAmethyst);
		OreDictionary.registerOre(CrystalConfig.oredict.oreOreDict, ModItems.dustCrystal);
		OreDictionary.registerOre(MagnesiumConfig.oredict.dustOreDict, ModItems.dustMagnesium);
		OreDictionary.registerOre(PhosphorusConfig.oredict.oreOreDict, ModItems.dustPhosphorus);
		OreDictionary.registerOre(SulfurConfig.oredict.dustOreDict, ModItems.dustSulfur);
		OreDictionary.registerOre(SilvaniteConfig.oredict.dustOreDict, ModItems.dustSilvanite);
		OreDictionary.registerOre(MerciliteConfig.oredict.dustOreDict, ModItems.dustMercilite);
		OreDictionary.registerOre(MythianConfig.oredict.dustOreDict, ModItems.dustMythian);
		OreDictionary.registerOre(DragiteConfig.oredict.dustOreDict, ModItems.dustDragite);
		OreDictionary.registerOre(FlariteConfig.oredict.dustOreDict, ModItems.dustFlarite);
		OreDictionary.registerOre(FureniumConfig.oredict.dustOreDict, ModItems.dustFurenium);
		OreDictionary.registerOre(BlackstoneConfig.oredict.dustOreDict, ModItems.dustBlackstone);
		OreDictionary.registerOre(BluestoneConfig.oredict.dustOreDict, ModItems.dustBluestone);
		OreDictionary.registerOre(PurplestoneConfig.oredict.dustOreDict, ModItems.dustPurplestone);
		OreDictionary.registerOre(AlloyBronzeConfig.oredict.dustOreDict, ModItems.dustBronze);
		OreDictionary.registerOre(AlloyCupronickelConfig.oredict.dustOreDict, ModItems.dustCupronickel);
		OreDictionary.registerOre(AlloyBrassConfig.oredict.dustOreDict, ModItems.dustBrass);
		OreDictionary.registerOre(AlloyRoseGoldConfig.oredict.dustOreDict, ModItems.dustRosegold);
		OreDictionary.registerOre(AlloySteelConfig.oredict.dustOreDict, ModItems.dustSteel);
		OreDictionary.registerOre(AlloyStainlessSteelConfig.oredict.dustOreDict, ModItems.dustStainlesssteel);
		OreDictionary.registerOre(AlloyNichromeConfig.oredict.dustOreDict, ModItems.dustNichrome);
		OreDictionary.registerOre(AlloyElectrumConfig.oredict.dustOreDict, ModItems.dustElectrum);
		OreDictionary.registerOre(AlloyStelliteConfig.oredict.dustOreDict, ModItems.dustStellite);
		OreDictionary.registerOre(AlloySilvamerConfig.oredict.dustOreDict, ModItems.dustSilvamer);
		OreDictionary.registerOre(AlloyUniumConfig.oredict.dustOreDict, ModItems.dustUnium);
		OreDictionary.registerOre(AlloyFenikisiteConfig.oredict.dustOreDict, ModItems.dustFenikisite);
		OreDictionary.registerOre(AlloyUltimiteConfig.oredict.dustOreDict, ModItems.dustUltimite);
		OreDictionary.registerOre(AlloyStrootiteConfig.oredict.dustOreDict, ModItems.dustStrootite);
		OreDictionary.registerOre(AlloySpeedoiConfig.oredict.dustOreDict, ModItems.dustSpeedoi);
		OreDictionary.registerOre(AlloyLegeniteConfig.oredict.dustOreDict, ModItems.dustLegenite);
		
		//Impure Dusts
		OreDictionary.registerOre(CopperConfig.oredict.dustImpureOreDict, ModItems.dustImpureCopper);
		OreDictionary.registerOre(TinConfig.oredict.dustImpureOreDict, ModItems.dustImpureTin);
		OreDictionary.registerOre(ZincConfig.oredict.dustImpureOreDict, ModItems.dustImpureZinc);
		OreDictionary.registerOre(NickelConfig.oredict.dustImpureOreDict, ModItems.dustImpureNickel);
		OreDictionary.registerOre(SilverConfig.oredict.dustImpureOreDict, ModItems.dustImpureSilver);
		OreDictionary.registerOre(AluminiumConfig.oredict.dustImpureOreDict, ModItems.dustImpureAluminium);
		OreDictionary.registerOre(TitaniumConfig.oredict.dustImpureOreDict, ModItems.dustImpureTitanium);
		OreDictionary.registerOre(ChromiumConfig.oredict.dustImpureOreDict, ModItems.dustImpureChromium);
		OreDictionary.registerOre(SiliconConfig.oredict.dustImpureOreDict, ModItems.dustImpureSilicon);
		OreDictionary.registerOre(CobaltConfig.oredict.dustImpureOreDict, ModItems.dustImpureCobalt);
		OreDictionary.registerOre(TungstenConfig.oredict.dustImpureOreDict, ModItems.dustImpureTungsten);
		OreDictionary.registerOre(LeadConfig.oredict.dustImpureOreDict, ModItems.dustImpureLead);
		OreDictionary.registerOre(PlatinumConfig.oredict.dustImpureOreDict, ModItems.dustImpurePlatinum);
		OreDictionary.registerOre(LithiumConfig.oredict.dustImpureOreDict, ModItems.dustImpureLithium);
		OreDictionary.registerOre(UraniumConfig.oredict.dustImpureOreDict, ModItems.dustImpureUranium);
		OreDictionary.registerOre(PlutoniumConfig.oredict.dustImpureOreDict, ModItems.dustImpurePlutonium);
		OreDictionary.registerOre(RubyConfig.oredict.dustImpureOreDict, ModItems.dustImpureRuby);
		OreDictionary.registerOre(SapphireConfig.oredict.dustImpureOreDict, ModItems.dustImpureSapphire);
		OreDictionary.registerOre(AmethystConfig.oredict.dustImpureOreDict, ModItems.dustImpureAmethyst);
		OreDictionary.registerOre(CrystalConfig.oredict.dustImpureOreDict, ModItems.dustImpureCrystal);
		OreDictionary.registerOre(MagnesiumConfig.oredict.dustImpureOreDict, ModItems.dustImpureMagnesium);
		OreDictionary.registerOre(PhosphorusConfig.oredict.dustImpureOreDict, ModItems.dustImpurePhosphorus);
		OreDictionary.registerOre(SulfurConfig.oredict.dustImpureOreDict, ModItems.dustImpureSulfur);
		OreDictionary.registerOre(SilvaniteConfig.oredict.dustImpureOreDict, ModItems.dustImpureSilvanite);
		OreDictionary.registerOre(MerciliteConfig.oredict.dustImpureOreDict, ModItems.dustImpureMercilite);
		OreDictionary.registerOre(MythianConfig.oredict.dustImpureOreDict, ModItems.dustImpureMythian);
		OreDictionary.registerOre(DragiteConfig.oredict.dustImpureOreDict, ModItems.dustImpureDragite);
		OreDictionary.registerOre(FlariteConfig.oredict.dustImpureOreDict, ModItems.dustImpureFlarite);
		OreDictionary.registerOre(FureniumConfig.oredict.dustImpureOreDict, ModItems.dustImpureFurenium);
		OreDictionary.registerOre(BlackstoneConfig.oredict.dustImpureOreDict, ModItems.dustImpureBlackstone);
		OreDictionary.registerOre(BluestoneConfig.oredict.dustImpureOreDict, ModItems.dustImpureBluestone);
		OreDictionary.registerOre(PurplestoneConfig.oredict.dustImpureOreDict, ModItems.dustImpurePurplestone);
		//They also work as a normal dust, because not many mods handle impure dusts
		OreDictionary.registerOre(CopperConfig.oredict.dustOreDict, ModItems.dustImpureCopper);
		OreDictionary.registerOre(TinConfig.oredict.dustOreDict, ModItems.dustImpureTin);
		OreDictionary.registerOre(ZincConfig.oredict.dustOreDict, ModItems.dustImpureZinc);
		OreDictionary.registerOre(NickelConfig.oredict.dustOreDict, ModItems.dustImpureNickel);
		OreDictionary.registerOre(SilverConfig.oredict.dustOreDict, ModItems.dustImpureSilver);
		OreDictionary.registerOre(AluminiumConfig.oredict.dustOreDict, ModItems.dustImpureAluminium);
		OreDictionary.registerOre(TitaniumConfig.oredict.dustOreDict, ModItems.dustImpureTitanium);
		OreDictionary.registerOre(ChromiumConfig.oredict.dustOreDict, ModItems.dustImpureChromium);
		OreDictionary.registerOre(SiliconConfig.oredict.dustOreDict, ModItems.dustImpureSilicon);
		OreDictionary.registerOre(CobaltConfig.oredict.dustOreDict, ModItems.dustImpureCobalt);
		OreDictionary.registerOre(TungstenConfig.oredict.dustOreDict, ModItems.dustImpureTungsten);
		OreDictionary.registerOre(LeadConfig.oredict.dustOreDict, ModItems.dustImpureLead);
		OreDictionary.registerOre(PlatinumConfig.oredict.dustOreDict, ModItems.dustImpurePlatinum);
		OreDictionary.registerOre(LithiumConfig.oredict.dustOreDict, ModItems.dustImpureLithium);
		OreDictionary.registerOre(UraniumConfig.oredict.dustOreDict, ModItems.dustImpureUranium);
		OreDictionary.registerOre(PlutoniumConfig.oredict.dustOreDict, ModItems.dustImpurePlutonium);
		OreDictionary.registerOre(RubyConfig.oredict.dustOreDict, ModItems.dustImpureRuby);
		OreDictionary.registerOre(SapphireConfig.oredict.dustOreDict, ModItems.dustImpureSapphire);
		OreDictionary.registerOre(AmethystConfig.oredict.dustOreDict, ModItems.dustImpureAmethyst);
		OreDictionary.registerOre(CrystalConfig.oredict.dustOreDict, ModItems.dustImpureCrystal);
		OreDictionary.registerOre(MagnesiumConfig.oredict.dustOreDict, ModItems.dustImpureMagnesium);
		OreDictionary.registerOre(PhosphorusConfig.oredict.dustOreDict, ModItems.dustImpurePhosphorus);
		OreDictionary.registerOre(SulfurConfig.oredict.dustOreDict, ModItems.dustImpureSulfur);
		OreDictionary.registerOre(SilvaniteConfig.oredict.dustOreDict, ModItems.dustImpureSilvanite);
		OreDictionary.registerOre(MerciliteConfig.oredict.dustOreDict, ModItems.dustImpureMercilite);
		OreDictionary.registerOre(MythianConfig.oredict.dustOreDict, ModItems.dustImpureMythian);
		OreDictionary.registerOre(DragiteConfig.oredict.dustOreDict, ModItems.dustImpureDragite);
		OreDictionary.registerOre(FlariteConfig.oredict.dustOreDict, ModItems.dustImpureFlarite);
		OreDictionary.registerOre(FureniumConfig.oredict.dustOreDict, ModItems.dustImpureFurenium);
		OreDictionary.registerOre(BlackstoneConfig.oredict.dustOreDict, ModItems.dustImpureBlackstone);
		OreDictionary.registerOre(BluestoneConfig.oredict.dustOreDict, ModItems.dustImpureBluestone);
		OreDictionary.registerOre(PurplestoneConfig.oredict.dustOreDict, ModItems.dustImpurePurplestone);
		
		//Tiny Dusts
		OreDictionary.registerOre(CopperConfig.oredict.dustTinyOreDict, ModItems.dustTinyCopper);
		OreDictionary.registerOre(TinConfig.oredict.dustTinyOreDict, ModItems.dustTinyTin);
		OreDictionary.registerOre(ZincConfig.oredict.dustTinyOreDict, ModItems.dustTinyZinc);
		OreDictionary.registerOre(NickelConfig.oredict.dustTinyOreDict, ModItems.dustTinyNickel);
		OreDictionary.registerOre(SilverConfig.oredict.dustTinyOreDict, ModItems.dustTinySilver);
		OreDictionary.registerOre(AluminiumConfig.oredict.dustTinyOreDict, ModItems.dustTinyAluminium);
		OreDictionary.registerOre(TitaniumConfig.oredict.dustTinyOreDict, ModItems.dustTinyTitanium);
		OreDictionary.registerOre(ChromiumConfig.oredict.dustTinyOreDict, ModItems.dustTinyChromium);
		OreDictionary.registerOre(SiliconConfig.oredict.dustTinyOreDict, ModItems.dustTinySilicon);
		OreDictionary.registerOre(CobaltConfig.oredict.dustTinyOreDict, ModItems.dustTinyCobalt);
		OreDictionary.registerOre(TungstenConfig.oredict.dustTinyOreDict, ModItems.dustTinyTungsten);
		OreDictionary.registerOre(LeadConfig.oredict.dustTinyOreDict, ModItems.dustTinyLead);
		OreDictionary.registerOre(PlatinumConfig.oredict.dustTinyOreDict, ModItems.dustTinyPlatinum);
		OreDictionary.registerOre(LithiumConfig.oredict.dustTinyOreDict, ModItems.dustTinyLithium);
		OreDictionary.registerOre(UraniumConfig.oredict.dustTinyOreDict, ModItems.dustTinyUranium);
		OreDictionary.registerOre(PlutoniumConfig.oredict.dustTinyOreDict, ModItems.dustTinyPlutonium);
		OreDictionary.registerOre(RubyConfig.oredict.oreOreDict, ModItems.dustTinyRuby);
		OreDictionary.registerOre(SapphireConfig.oredict.oreOreDict, ModItems.dustTinySapphire);
		OreDictionary.registerOre(AmethystConfig.oredict.oreOreDict, ModItems.dustTinyAmethyst);
		OreDictionary.registerOre(CrystalConfig.oredict.oreOreDict, ModItems.dustTinyCrystal);
		OreDictionary.registerOre(MagnesiumConfig.oredict.dustTinyOreDict, ModItems.dustTinyMagnesium);
		OreDictionary.registerOre(PhosphorusConfig.oredict.oreOreDict, ModItems.dustTinyPhosphorus);
		OreDictionary.registerOre(SulfurConfig.oredict.dustTinyOreDict, ModItems.dustTinySulfur);
		OreDictionary.registerOre(SilvaniteConfig.oredict.dustTinyOreDict, ModItems.dustTinySilvanite);
		OreDictionary.registerOre(MerciliteConfig.oredict.dustTinyOreDict, ModItems.dustTinyMercilite);
		OreDictionary.registerOre(MythianConfig.oredict.dustTinyOreDict, ModItems.dustTinyMythian);
		OreDictionary.registerOre(DragiteConfig.oredict.dustTinyOreDict, ModItems.dustTinyDragite);
		OreDictionary.registerOre(FlariteConfig.oredict.dustTinyOreDict, ModItems.dustTinyFlarite);
		OreDictionary.registerOre(FureniumConfig.oredict.dustTinyOreDict, ModItems.dustTinyFurenium);
		OreDictionary.registerOre(BlackstoneConfig.oredict.dustTinyOreDict, ModItems.dustTinyBlackstone);
		OreDictionary.registerOre(BluestoneConfig.oredict.dustTinyOreDict, ModItems.dustTinyBluestone);
		OreDictionary.registerOre(PurplestoneConfig.oredict.dustTinyOreDict, ModItems.dustTinyPurplestone);
		OreDictionary.registerOre(AlloyBronzeConfig.oredict.dustTinyOreDict, ModItems.dustTinyBronze);
		OreDictionary.registerOre(AlloyCupronickelConfig.oredict.dustTinyOreDict, ModItems.dustTinyCupronickel);
		OreDictionary.registerOre(AlloyBrassConfig.oredict.dustTinyOreDict, ModItems.dustTinyBrass);
		OreDictionary.registerOre(AlloyRoseGoldConfig.oredict.dustTinyOreDict, ModItems.dustTinyRosegold);
		OreDictionary.registerOre(AlloySteelConfig.oredict.dustTinyOreDict, ModItems.dustTinySteel);
		OreDictionary.registerOre(AlloyStainlessSteelConfig.oredict.dustTinyOreDict, ModItems.dustTinyStainlesssteel);
		OreDictionary.registerOre(AlloyNichromeConfig.oredict.dustTinyOreDict, ModItems.dustTinyNichrome);
		OreDictionary.registerOre(AlloyElectrumConfig.oredict.dustTinyOreDict, ModItems.dustTinyElectrum);
		OreDictionary.registerOre(AlloyStelliteConfig.oredict.dustTinyOreDict, ModItems.dustTinyStellite);
		OreDictionary.registerOre(AlloySilvamerConfig.oredict.dustTinyOreDict, ModItems.dustTinySilvamer);
		OreDictionary.registerOre(AlloyUniumConfig.oredict.dustTinyOreDict, ModItems.dustTinyUnium);
		OreDictionary.registerOre(AlloyFenikisiteConfig.oredict.dustTinyOreDict, ModItems.dustTinyFenikisite);
		OreDictionary.registerOre(AlloyUltimiteConfig.oredict.dustTinyOreDict, ModItems.dustTinyUltimite);
		OreDictionary.registerOre(AlloyStrootiteConfig.oredict.dustTinyOreDict, ModItems.dustTinyStrootite);
		OreDictionary.registerOre(AlloySpeedoiConfig.oredict.dustTinyOreDict, ModItems.dustTinySpeedoi);
		OreDictionary.registerOre(AlloyLegeniteConfig.oredict.dustTinyOreDict, ModItems.dustTinyLegenite);

		//Nuggets
		OreDictionary.registerOre(CopperConfig.oredict.nuggetOreDict, ModItems.nuggetCopper);
		OreDictionary.registerOre(TinConfig.oredict.nuggetOreDict, ModItems.nuggetTin);
		OreDictionary.registerOre(ZincConfig.oredict.nuggetOreDict, ModItems.nuggetZinc);
		OreDictionary.registerOre(NickelConfig.oredict.nuggetOreDict, ModItems.nuggetNickel);
		OreDictionary.registerOre(SilverConfig.oredict.nuggetOreDict, ModItems.nuggetSilver);
		OreDictionary.registerOre(AluminiumConfig.oredict.nuggetOreDict, ModItems.nuggetAluminium);
		OreDictionary.registerOre(TitaniumConfig.oredict.nuggetOreDict, ModItems.nuggetTitanium);
		OreDictionary.registerOre(ChromiumConfig.oredict.nuggetOreDict, ModItems.nuggetChromium);
		OreDictionary.registerOre(CobaltConfig.oredict.nuggetOreDict, ModItems.nuggetCobalt);
		OreDictionary.registerOre(TungstenConfig.oredict.nuggetOreDict, ModItems.nuggetTungsten);
		OreDictionary.registerOre(LeadConfig.oredict.nuggetOreDict, ModItems.nuggetLead);
		OreDictionary.registerOre(PlatinumConfig.oredict.nuggetOreDict, ModItems.nuggetPlatinum);
		OreDictionary.registerOre(LithiumConfig.oredict.nuggetOreDict, ModItems.nuggetLithium);
		OreDictionary.registerOre(UraniumConfig.oredict.nuggetOreDict, ModItems.nuggetUranium);
		OreDictionary.registerOre(PlutoniumConfig.oredict.nuggetOreDict, ModItems.nuggetPlutonium);
		OreDictionary.registerOre(RubyConfig.oredict.oreOreDict, ModItems.nuggetRuby);
		OreDictionary.registerOre(SapphireConfig.oredict.oreOreDict, ModItems.nuggetSapphire);
		OreDictionary.registerOre(AmethystConfig.oredict.oreOreDict, ModItems.nuggetAmethyst);
		OreDictionary.registerOre(CrystalConfig.oredict.oreOreDict, ModItems.nuggetCrystal);
		OreDictionary.registerOre(MagnesiumConfig.oredict.nuggetOreDict, ModItems.nuggetMagnesium);
		OreDictionary.registerOre(SilvaniteConfig.oredict.nuggetOreDict, ModItems.nuggetSilvanite);
		OreDictionary.registerOre(MerciliteConfig.oredict.nuggetOreDict, ModItems.nuggetMercilite);
		OreDictionary.registerOre(MythianConfig.oredict.nuggetOreDict, ModItems.nuggetMythian);
		OreDictionary.registerOre(DragiteConfig.oredict.nuggetOreDict, ModItems.nuggetDragite);
		OreDictionary.registerOre(FlariteConfig.oredict.nuggetOreDict, ModItems.nuggetFlarite);
		OreDictionary.registerOre(FureniumConfig.oredict.nuggetOreDict, ModItems.nuggetFurenium);
		OreDictionary.registerOre(AlloyBronzeConfig.oredict.nuggetOreDict, ModItems.nuggetBronze);
		OreDictionary.registerOre(AlloyCupronickelConfig.oredict.nuggetOreDict, ModItems.nuggetCupronickel);
		OreDictionary.registerOre(AlloyBrassConfig.oredict.nuggetOreDict, ModItems.nuggetBrass);
		OreDictionary.registerOre(AlloyRoseGoldConfig.oredict.nuggetOreDict, ModItems.nuggetRosegold);
		OreDictionary.registerOre(AlloySteelConfig.oredict.nuggetOreDict, ModItems.nuggetSteel);
		OreDictionary.registerOre(AlloyStainlessSteelConfig.oredict.nuggetOreDict, ModItems.nuggetStainlesssteel);
		OreDictionary.registerOre(AlloyNichromeConfig.oredict.nuggetOreDict, ModItems.nuggetNichrome);
		OreDictionary.registerOre(AlloyElectrumConfig.oredict.nuggetOreDict, ModItems.nuggetElectrum);
		OreDictionary.registerOre(AlloyStelliteConfig.oredict.nuggetOreDict, ModItems.nuggetStellite);
		OreDictionary.registerOre(AlloySilvamerConfig.oredict.nuggetOreDict, ModItems.nuggetSilvamer);
		OreDictionary.registerOre(AlloyUniumConfig.oredict.nuggetOreDict, ModItems.nuggetUnium);
		OreDictionary.registerOre(AlloyFenikisiteConfig.oredict.nuggetOreDict, ModItems.nuggetFenikisite);
		OreDictionary.registerOre(AlloyUltimiteConfig.oredict.nuggetOreDict, ModItems.nuggetUltimite);
		OreDictionary.registerOre(AlloyStrootiteConfig.oredict.nuggetOreDict, ModItems.nuggetStrootite);
		OreDictionary.registerOre(AlloySpeedoiConfig.oredict.nuggetOreDict, ModItems.nuggetSpeedoi);
		OreDictionary.registerOre(AlloyLegeniteConfig.oredict.nuggetOreDict, ModItems.nuggetLegenite);
		
		//Refined Blocks
		OreDictionary.registerOre(CopperConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 0));
		OreDictionary.registerOre(TinConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 1));
		OreDictionary.registerOre(ZincConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 2));
		OreDictionary.registerOre(NickelConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 3));
		OreDictionary.registerOre(SilverConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 4));
		OreDictionary.registerOre(AluminiumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 5));
		OreDictionary.registerOre(TitaniumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 6));
		OreDictionary.registerOre(ChromiumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 7));
		OreDictionary.registerOre(SiliconConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 8));
		OreDictionary.registerOre(CobaltConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 9));
		OreDictionary.registerOre(TungstenConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 10));
		OreDictionary.registerOre(LeadConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 11));
		OreDictionary.registerOre(PlatinumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 12));
		OreDictionary.registerOre(LithiumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 13));
		OreDictionary.registerOre(UraniumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 14));
		OreDictionary.registerOre(PlutoniumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined1, 1, 15));
		OreDictionary.registerOre(RubyConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 0));
		OreDictionary.registerOre(SapphireConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 1));
		OreDictionary.registerOre(AmethystConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 2));
		OreDictionary.registerOre(CrystalConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 3));
		OreDictionary.registerOre(MagnesiumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 4));
		OreDictionary.registerOre(PhosphorusConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 5));
		OreDictionary.registerOre(SulfurConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 6));
		OreDictionary.registerOre(SilvaniteConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 7));
		OreDictionary.registerOre(MerciliteConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 8));
		OreDictionary.registerOre(MythianConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 9));
		OreDictionary.registerOre(DragiteConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 10));
		OreDictionary.registerOre(FlariteConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 11));
		OreDictionary.registerOre(FureniumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 12));
		OreDictionary.registerOre(BlackstoneConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 13));
		OreDictionary.registerOre(BluestoneConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 14));
		OreDictionary.registerOre(PurplestoneConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 15));
		OreDictionary.registerOre(AlloyBronzeConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined2, 1, 0));
		OreDictionary.registerOre(AlloyCupronickelConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 1));
		OreDictionary.registerOre(AlloyBrassConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 2));
		OreDictionary.registerOre(AlloyRoseGoldConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 3));
		OreDictionary.registerOre(AlloySteelConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 4));
		OreDictionary.registerOre(AlloyStainlessSteelConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 5));
		OreDictionary.registerOre(AlloyNichromeConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 6));
		OreDictionary.registerOre(AlloyElectrumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 7));
		OreDictionary.registerOre(AlloyStelliteConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 8));
		OreDictionary.registerOre(AlloySilvamerConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 9));
		OreDictionary.registerOre(AlloyUniumConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 10));
		OreDictionary.registerOre(AlloyFenikisiteConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 11));
		OreDictionary.registerOre(AlloyUltimiteConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 12));
		OreDictionary.registerOre(AlloyStrootiteConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 13));
		OreDictionary.registerOre(AlloySpeedoiConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 14));
		OreDictionary.registerOre(AlloyLegeniteConfig.oredict.blockOreDict, new ItemStack(ModBlocks.blockRefined3, 1, 15));
		
		
		if (AluminiumConfig.oredict.americanSupport) {
			//You're WRONG. WRONG I TELL THEE! Might as well spell it "aloominum"
			OreDictionary.registerOre("oreAluminum", new ItemStack(ModBlocks.blockOre1, 1, 5));
			OreDictionary.registerOre("oreAluminum", ModItems.oreAluminium);
			OreDictionary.registerOre("ingotAluminum", ModItems.ingotAluminium);
			OreDictionary.registerOre("dustAluminum", ModItems.dustAluminium);
			OreDictionary.registerOre("dustImpureAluminum", ModItems.dustImpureAluminium);
			OreDictionary.registerOre("dustTinyAluminum", ModItems.dustTinyAluminium);
			OreDictionary.registerOre("nuggetAluminum", ModItems.nuggetAluminium);
			OreDictionary.registerOre("blockAluminum", new ItemStack(ModBlocks.blockRefined1, 1, 5));
		}
	}

}
